### ISSUE TITLE
when we start the music it is not going in one flow like the original one .There is a lag in between

### ISSUE THREAD

**Issue by bluegroundgreensky** [bluegroundgreensky/soundspace#1]

**Comment by AbhayJhouta** [comment]
is this issue still there ?

**Comment by bluegroundgreensky** [comment]
yes plz help

**Comment by AbhayJhouta** [comment]
ok actually i have found the solution will give u the request soon

**Comment by AbhayJhouta** [comment]
Please look at new pull request ,thing is music progress will now only change when user will manually change seek bar, not  with the seekbar's progress  which is moving continuously when music is playing

**Comment by bluegroundgreensky** [comment]
ok  I got it . I will look at it in some time.thanks

**Comment by bluegroundgreensky** [comment]
thanks .Now i got to why it was lagging
